---
title: "A new look at the last decade of research on the rise of harmful airborne cyanobacteria and microalgae and its broad consequences"

author:
- Kinga Wiśniewska:
    institute:
    - UW
    email: kinga.wisniewska@uwr.edu.pl
    correspondence: true
- Sylwia Śliwińska-Wilczewska:
    institute:
    - UG1
    email: sylwia.sliwinska-wilczewska@ug.edu.pl
- Anita U. Lewandowska:
    institute:
    - UG2
    email: anita.lewandowska@ug.edu.pl
institute:
- UW: Department of Climatology and Atmosphere Protection, Faculty of Earth Sciences and Environmental Management, University of Wroclaw, Kosiby 8 St., 51–621 Wroclaw, Poland
- UG1: Division of Marine Ecosystems Functioning, Faculty of Oceanography and Geography, University of Gdańsk, Al. Marsz. Piłsudskiego 46, 81-378 Gdynia, Poland
- UG2: Division of Chemical Oceanography and Marine Geology, Faculty of Oceanography and Geography, University of Gdańsk, Al. Marsz. Piłsudskiego 46, 81-378 Gdynia, Poland
output:
  bookdown::word_document2:
    reference_docx: Template.docx
    code-folding: show
    keep_md: yes
    fig.caption: yes
    toc: FALSE
    pandoc_args:
    - "--lua-filter=scholarly-metadata.lua"
    - "--lua-filter=author-info-blocks.lua"
  html_document:
    df_print: paged
  word_document:
    reference_docx: Template.docx
    code-folding: show
    keep_md: yes
    fig.caption: yes
    toc: FALSE
    pandoc_args:
    - "--lua-filter=scholarly-metadata.lua"
    - "--lua-filter=author-info-blocks.lua"
    - "--lua-filter=custom_filter.lua"
bibliography:
- PicoBaltic.bib
- packages.bib
- faultycitations.bib
csl: "nature-communications.csl"
---

```{r, import libraries, include = FALSE}
library(tidyverse)
library(glue)
library(googlesheets4)
googlesheets4:: gs4_deauth()
#library(kableExtra)
library(flextable)
library(officer)
library(knitr)
library(readxl)
library(stringr)
library(rmarkdown)
library(gdtools)
#library(trackdown)
options(knitr.table.format = "word_document2", knitr.kable.NA = '') 
```

```{r, save package citations, include = FALSE}
knitr:: write_bib(c("tidyverse", "glue", "googlesheets4", "kableExtra"), "packages.bib")
```

```{r defining filepaths, include = FALSE}
FiguresFP <- file.path("..", "Output", "Figures")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

# Supporting Information {.unnumbered}


